"use client";

import { useChat, Message } from "ai/react";
import { useRef, useEffect } from "react";

export default function ChatPage() {
  const { messages, input, handleInputChange, handleSubmit, isLoading } =
    useChat({
      api: process.env.NEXT_PUBLIC_API_URL
        ? `${process.env.NEXT_PUBLIC_API_URL}/api/chat`
        : "http://localhost:8000/api/chat",
    });

  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages, isLoading]);

  return (
    <div className="max-w-4xl mx-auto px-4 py-8 flex flex-col h-[calc(100vh-84px)]">
      <div className="mb-6 flex-shrink-0">
        <h1 className="text-2xl font-bold text-primary flex items-center gap-2">
          <span>CourtVision Assistant</span>
          <span className="bg-orange/20 text-orange text-xs px-2 py-0.5 rounded-full border border-orange/40 font-mono">
            BETA
          </span>
        </h1>
        <p className="text-secondary text-sm mt-1">
          Ask for breaking news, player stats, or general basketball analysis.
        </p>
      </div>

      <div
        ref={scrollRef}
        className="flex-1 overflow-y-auto bg-surface border border-border rounded-xl p-4 md:p-6 mb-4 space-y-4"
      >
        {messages.length === 0 ? (
          <div className="h-full flex flex-col items-center justify-center text-center text-secondary opacity-60">
            <span className="text-4xl mb-3">🏀</span>
            <p className="max-w-xs leading-relaxed">
              I'm an AI specialized in NBA stats and news. Ask me who won last
              night, or who is leading the MVP race!
            </p>
          </div>
        ) : (
          messages.map((m: Message) => (
            <div
              key={m.id}
              className={`flex flex-col max-w-[85%] ${
                m.role === "user" ? "ml-auto items-end" : "mr-auto items-start"
              }`}
            >
              <span className="text-[10px] text-dim font-bold uppercase tracking-widest mb-1.5 ml-1">
                {m.role === "user" ? "You" : "CourtVision AI"}
              </span>
              <div
                className={`px-4 py-2.5 rounded-2xl text-sm leading-relaxed whitespace-pre-wrap ${
                  m.role === "user"
                    ? "bg-orange text-white rounded-br-sm"
                    : "bg-surfaceHigh text-primary border border-border rounded-bl-sm"
                }`}
              >
                {m.content}
              </div>
            </div>
          ))
        )}

        {isLoading && messages[messages.length - 1]?.role === "user" && (
          <div className="flex flex-col max-w-[85%] mr-auto items-start animate-pulse">
            <span className="text-[10px] text-dim font-bold uppercase tracking-widest mb-1.5 ml-1">
              CourtVision AI
            </span>
            <div className="px-4 py-4 rounded-2xl bg-surfaceHigh border border-border rounded-bl-sm flex gap-1.5 items-center">
              <div className="w-1.5 h-1.5 bg-orange rounded-full animate-bounce delay-75"></div>
              <div className="w-1.5 h-1.5 bg-orange rounded-full animate-bounce delay-150"></div>
              <div className="w-1.5 h-1.5 bg-orange rounded-full animate-bounce delay-300"></div>
            </div>
          </div>
        )}
      </div>

      <form
        onSubmit={handleSubmit}
        className="flex gap-3 bg-surface border border-border p-2 rounded-xl focus-within:border-orange/50 transition-colors flex-shrink-0"
      >
        <input
          className="flex-1 bg-transparent border-none text-primary placeholder-dim px-3 py-2 text-sm focus:outline-none"
          value={input}
          onChange={handleInputChange}
          placeholder="Type your question..."
          disabled={isLoading}
        />
        <button
          type="submit"
          disabled={isLoading || !input.trim()}
          className="bg-orange hover:bg-orangeLight disabled:bg-surfaceHigh disabled:text-dim text-white font-semibold px-6 py-2 rounded-lg text-sm transition-colors"
        >
          Send
        </button>
      </form>
      <p className="text-center text-[10px] text-dim mt-3 flex-shrink-0">
        Responses are generated by AI and may be occasionally inaccurate.
      </p>
    </div>
  );
}
